import subprocess
import tempfile
import os
from agents.extract_function_name import inject_function_call
from stateAgent.stateAgent import stateAgent 


LANGUAGE_CONFIG = {
    "python": {
        "image": "python:3.10",
        "filename": "main.py",
        "command": ["python", "main.py"]
    }
}


def run_code(code: str, language = "python"):
    if language not in LANGUAGE_CONFIG:
        return {
            "stdout": "",
            "stderr": f"Language '{language}' not supported",
            "exit_code": -1
        }

    config = LANGUAGE_CONFIG[language]

    with tempfile.TemporaryDirectory() as tmpdir:
        file_path = os.path.join(tmpdir, config["filename"])

        with open(file_path, "w", encoding="utf-8") as f:
            f.write(code)

        docker_cmd = [
            "docker", "run", "--rm",
            "--network", "none",
            "--cpus", "1",
            "--memory", "256m",
            "-v", f"{tmpdir}:/app",
            "-w", "/app",
            config["image"],
            *config["command"]
        ]

        try:
            result = subprocess.run(
                docker_cmd,
                capture_output=True,
                text=True,
                timeout=10
            )

            return {
                "code": code,
                "stdout": result.stdout.strip(),
                "stderr": result.stderr.strip(),
                "exit_code": result.returncode
            }

        except subprocess.TimeoutExpired:
            return {
                "stdout": "",
                "stderr": "Execution timed out",
                "exit_code": -1
            }
import re

def sanitize_python_code(code: str) -> str:
    if not code:
        return ""

    code = code.strip()

    # remove ```python ... ``` or ``` ... ```
    if code.startswith("```"):
        code = re.sub(r"^```[a-zA-Z]*\n?", "", code)
        code = re.sub(r"\n?```$", "", code)

    return code.strip()


def contains_function(code: str) -> bool:
    return bool(re.search(r"\bdef\s+\w+\s*\(", code))


def execute_user_code(state: stateAgent):
    raw_code = state.get("Synthesizer")

    # 🛑 Nothing to execute
    if not raw_code:
        return {
            "status": "no_output",
            "message": "No code generated by agent"
        }

    clean_code = sanitize_python_code(raw_code)

    # 🛑 Not executable code
    if not contains_function(clean_code):
        return {
            "status": "text_only",
            "output": clean_code
        }

    inputs = state.get("param", [])

    final_code = inject_function_call(clean_code, inputs)
    result = run_code(final_code)

    if result["exit_code"] == 0:
        return {
            "status": "success",
            "code": clean_code,
            "output": result["stdout"]
        }

    return {
        "status": "error",
        "code": clean_code,
        "error": result["stderr"],
        "exit_code": result["exit_code"]
    }
